# Generated by Django 2.1.5 on 2020-01-04 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('VacationId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('EmpName', models.CharField(max_length=100)),
                ('EmpId', models.CharField(max_length=30)),
                ('vacationStartdate', models.DateTimeField()),
                ('vacationEnddate', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='vacationId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calen.Vacation'),
        ),
    ]
