# Generated by Django 2.1.5 on 2019-12-15 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
    ]
