# Generated by Django 2.1.5 on 2019-12-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calen', '0002_remove_event_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpName', models.CharField(max_length=100)),
                ('EmpId', models.CharField(max_length=30)),
                ('vacationStartdate', models.DateTimeField()),
                ('vacationEnddate', models.DateTimeField()),
            ],
        ),
    ]
