# Generated by Django 2.2.5 on 2020-01-04 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.AlterField(
            model_name='employee',
            name='EmpId',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
